// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDt4_lNW_K0WJM4cTL8WeEytUN3_Q_Nmfk',
    appId: '1:150293150539:web:4fceb75b92bcb3b89b46ce',
    messagingSenderId: '150293150539',
    projectId: 'privy-nephro',
    authDomain: 'privy-nephro.firebaseapp.com',
    databaseURL: 'https://privy-nephro-default-rtdb.firebaseio.com',
    storageBucket: 'privy-nephro.firebasestorage.app',
    measurementId: 'G-DGWX9TP9RD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtg68dyg6sX5sl8KhfofhOs0nsrDOV6AE',
    appId: '1:150293150539:android:8b4685a0b05e24bd9b46ce',
    messagingSenderId: '150293150539',
    projectId: 'privy-nephro',
    databaseURL: 'https://privy-nephro-default-rtdb.firebaseio.com',
    storageBucket: 'privy-nephro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTzPlPvl5Q9Lvf_s9KC-ioaM-wpQGxfEg',
    appId: '1:150293150539:ios:aa7dfdead414dbdb9b46ce',
    messagingSenderId: '150293150539',
    projectId: 'privy-nephro',
    databaseURL: 'https://privy-nephro-default-rtdb.firebaseio.com',
    storageBucket: 'privy-nephro.firebasestorage.app',
    iosBundleId: 'com.privynephro.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTzPlPvl5Q9Lvf_s9KC-ioaM-wpQGxfEg',
    appId: '1:150293150539:ios:49589eee308ab2a39b46ce',
    messagingSenderId: '150293150539',
    projectId: 'privy-nephro',
    databaseURL: 'https://privy-nephro-default-rtdb.firebaseio.com',
    storageBucket: 'privy-nephro.firebasestorage.app',
    iosBundleId: 'com.example.privy181125',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDt4_lNW_K0WJM4cTL8WeEytUN3_Q_Nmfk',
    appId: '1:150293150539:web:e8e1d8cfbc31ce629b46ce',
    messagingSenderId: '150293150539',
    projectId: 'privy-nephro',
    authDomain: 'privy-nephro.firebaseapp.com',
    databaseURL: 'https://privy-nephro-default-rtdb.firebaseio.com',
    storageBucket: 'privy-nephro.firebasestorage.app',
    measurementId: 'G-CFXXF8RZK7',
  );
}